#ifndef __P_A5_TAB_REVA_H
#define __P_A5_TAB_REVA_H

//#define BOARD_MAINOSC		12000000

#ifdef CONFIG_BUS_SPEED_166MHZ
#define MASTER_CLOCK		166000000
#define BOARD_PLLA_MULA		82
#endif

#ifdef CONFIG_BUS_SPEED_116MHZ
#define MASTER_CLOCK		116000000
#define BOARD_PLLA_MULA		57
#endif


#define BOARD_CKGR_PLLA		(AT91C_CKGR_SRCA | AT91C_CKGR_OUTA_0)
#define BOARD_PLLACOUNT		(0x3F << 8)
#define BOARD_MULA		((AT91C_CKGR_MULA << 2) & (BOARD_PLLA_MULA << 18))
#define BOARD_DIVA		(AT91C_CKGR_DIVA & 1)

/*#define BOARD_PRESCALER_MAIN_CLOCK	(AT91C_PMC_PLLADIV2_2 \
					| AT91C_PMC_MDIV_3 \
					| AT91C_PMC_CSS_MAIN_CLK)*/

#define BOARD_PRESCALER_PLLA		(AT91C_PMC_H32MXDIV_H32MXDIV2 \
					| AT91C_PMC_PLLADIV2_2 \
					| AT91C_PMC_MDIV_3 \
					| AT91C_PMC_CSS_PLLA_CLK)

#define PLLA_SETTINGS		(BOARD_CKGR_PLLA | \
				BOARD_PLLACOUNT | \
				BOARD_MULA | \
				BOARD_DIVA)


#define USART_BASE			(AT91C_BASE_FLEXCOM1 + 0x0200)
#define CONFIG_SYS_DBGU_RXD_PIN		AT91C_PIN_PA(23)
#define CONFIG_SYS_DBGU_TXD_PIN		AT91C_PIN_PA(24)
#define CONFIG_SYS_DBGU_ID		AT91C_ID_FLEXCOM1


#define CONFIG_SYS_BASE_SDHC	AT91C_BASE_SDHC0
#define CONFIG_SYS_ID_SDHC	AT91C_ID_SDMMC0


#endif
